name: Rubber Skull
favicon: null
layout_spectrum: 0.49573
typography_spectrum: 0.24799415306188166
title: Rubber Skull
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0e0809'
    - '#52534e'
    - '#8b918c'
    - '#b5b7ba'
  brandStrength: 0.5893178570549935
  lightness: 0.5251568332314491
  saturation: 0.16602348652668297
  rhythmicContrast: 0.7499434272758663
purpose: []
