typography_spectrum: 0.7530924917664379
color:
  saturation: 0.625
  brandStrength: 0.1875
  rhythmicContrast: 0.75
  brandColors:
    - '#ffffff'
    - '#0e0809'
    - '#52534e'
    - '#8b918c'
    - '#b5b7ba'
  lightness: 0.4375
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.28989419899880886
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Aron Gagliardo
  email: arongagliardo@sbcglobal.net
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/24d7a723-8b07-492d-988e-bfb6e64ad340.jpg
name: FOK
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Music
    id: 6eb372f3-65a3-4627-a33d-90aa6777d09b
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Rubber Skull
description: funky surfer death!
purpose: []
