name: Rubber Skull
favicon: null
layout_spectrum: 0.5166698200628161
typography_spectrum: 0.24799415306188166
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5893178570549935
  lightness: 0.5251568332314491
  saturation: 0.16602348652668297
  rhythmicContrast: 0.7499434272758663
purpose: []
