name: Rubber Skull
favicon: null
layout_spectrum: 0.00071
typography_spectrum: 0
title: Rubber Skull
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0e0809'
    - '#52534e'
    - '#8b918c'
    - '#b5b7ba'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
